### ISSUE TITLE
forceRefresh is not working for invisible mode

### ISSUE THREAD

**Issue by hintbox** [Nika0000/cloudflare_turnstile#10]
Hi, i received token from invisible mode and consume it at server side. Depends on requirements like "account already available or not found" etc from server response, i sent some information with turnstile token to my api. Although, "CloudflareTurnstile.invisible" gives same token which is cannot be consumed twice for verification by cloudflare at server side. On the other hand, new token is received when token is expired at client side.

"turnstile?.refresh(forceRefresh: true)"

Thank you

**Comment by Nika0000** [comment]
Hi,

Ah, I see  the issue you're referring to, and it`s been fixed in [new version](https://pub.dev/packages/cloudflare_turnstile).

You can force refresh the token using:
```dart
final turnstile = CloudflareTurnstile.invisible(
  siteKey: '1x00000000000000000000BB',
);

// You can force a new token generation which will start
// a new Turnstile challenge
await turnstile.refresh();

// if you don`t want to generate a new token when there's 
// already a valid one that hasn`t expired, you can use
await turnstile.refresh(forceRefresh: false)

// Alternatively, you can also retrieve a new token
await turnstile.getToken();

// retrive the current token without triggering a new challange
var token = turnstile.token;
```

Additionally, in invisible mode automatically refreshes the token when it expires.
However, before making an API Request, make sure the token has not expired:

```dart
bool isExpired = await turnstile.isExpired();
```

> If the token is expired, you may want to refresh it or handle the situation accordingly.

Tip: When a token is generated, you should call `turnstile.dispose()` when you no longer need the Turnstile instance. This helps disable the WebView and optimize performance. After disposing of the Turnstile, if you need a new token, you can simply call `turnstile.getToken()` again to create a fresh instance. Remember that the token has a lifetime of 5 minutes, so if your API request could potentially take longer than that, make sure to manage your timing accordingly. Finally, always `dispose` of the Turnstile instance when you're done with it to free up resources.

**Comment by hintbox** [comment]
hi, @Nika0000 can you add a listener for token receiving, error etc. like visible mode has

**Comment by Nika0000** [comment]
> hi, @Nika0000 can you add a listener for token receiving, error etc. like visible mode has

I think I'll add it to the next release.

**Comment by hintbox** [comment]
waiting your next release, thank you @Nika0000 🙏

**Comment by Nika0000** [comment]
> hi @Nika0000, any updates? thank you

Hi, 
Probably next week.
